Project: ifk-smhi v.0.1.1 released
Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io pull request #50
Opened 2023-03-29 20:34 UTC by docNord

Closes #49.

- [x] Write article
- [ ] Mesan example
- [ ] Metfcts example
- [x] Metobs example
- [x] Strang example
- [x] Link to @mgcth personal site

2023-03-30 22:00 UTC, mgcth requested changes
Looks good! You're a way better writer.

External links should open in new windows/tabs. Should we convert the English legends etc. to Swedish?

2023-03-30 22:00 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +För Klimatets GitHub](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi).
```suggestion
Källkoden är tillgänglig under MIT-licens (fritt användande) på
<a href="https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi"
target="_blank">Ingenjörsarbete För Klimatets GitHub</a>.
```

2023-03-30 22:00 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +har modifierats från originalartikeln på [mladen.gibanica.net](https://mladen.gibanica.net/posts/ifk-smhi).
```suggestion
har modifierats från originalartikeln på
<a href="https://mladen.gibanica.net/posts/ifk-smhi"
target="_blank">mladen.gibanica.net</a>.
```

2023-03-30 22:00 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +Observera attde tre senaste månaderna vanligtvis saknas från `"corrected-archive"`.
```suggestion
Observera att de tre senaste månaderna vanligtvis saknas från `"corrected-archive"`.
```

2023-03-31 04:01 UTC, docNord commented
I can translate the figures as well, sure. I will also add two more examples as discussed previously.

2023-04-01 10:13 UTC, mgcth requested changes
Really nice examples!

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +annars endast finns tillgängliga för ett fåtal stationer i landet. Denna princip
Strange sentence here `... komplicerad annars ...`

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +target="_blank">SMHIs API-sida</a>m en en intressant parameter ute i skärgården
```suggestion
target="_blank">SMHIs API-sida</a>. En intressant parameter ute i skärgården
```

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +Och med hjälp av numpy kan vi sluta oss  till att den förväntade medelhastigheten
```suggestion
Och med hjälp av numpy kan vi sluta oss till att den förväntade medelhastigheten
```

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +client.gust
```suggestion
data.gust
```
Does this work? Is gust part of the pandas dataframe?

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +np.average(data.gust)
```suggestion
np.mean(data.gust)
```
Is `average` an alias for `mean`?

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
>      paper_bgcolor="rgba(250, 250, 250, 1)",
Could we add below this `updae_layout`

```python
fig.update_yaxes(
    scaleanchor="x",
    scaleratio=1,
)
```

2023-04-01 10:13 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +        data["Global irradiance [W/m²] 1999-01-01T00:00:00+00:00 daily"]},
```suggestion
        marker={
            "color": data["Global irradiance [W/m²] 1999-01-01T00:00:00+00:00 daily"]},
            "colorbar": {"title": "[W/m²]"}
        }
```

2023-04-01 10:54 UTC, mgcth requested changes
Looks good. So `data.gust` works? Amazing...

You will need to upload the data files to our storage box also, you can save them as

`fig.write_html("file_name.html", include_plotlyjs="cdn")`

2023-04-01 10:54 UTC, mgcth commented on content/posts/ifk-smhi-2023-03-29.md
> +    fig.update_yaxes(
```suggestion
fig.update_yaxes(
```

2023-04-02 08:53 UTC, mgcth approved these changes
Looks great! Let's see how it renders :)

2023-04-02 09:38 UTC, merged

2023-04-02 09:45 UTC, docNord commented
The Strang example does not generate data @mgcth . Is it your addition which is causing there to be a different result from what you published at your personal page?

2023-04-02 10:00 UTC, docNord commented
Found the problem. Will fix.

2023-04-03 20:49 UTC, mgcth commented
@docNord, can we delete this branch?

2023-04-03 20:50 UTC, docNord commented
Yes

On Mon, 3 Apr 2023, 22:49 Mladen Gibanica, ***@***.***> wrote:

> @docNord <https://github.com/docNord>, can we delete this branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io/pull/50#issuecomment-1494961649>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7PLB7DJHMF2GHBKBCYUGLW7MZUTANCNFSM6AAAAAAWMMIQLQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.
> ***@***.***>
>