AW report 2023-04-06
Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io pull request #59
Opened 2023-04-07 07:32 UTC by docNord

Short note on pustervik AW.

2023-04-07 09:14 UTC, mgcth requested changes

2023-04-07 09:14 UTC, mgcth commented on content/posts/event-aw-2023-04-06.md
> +tags: Politik, vetenskap, klimat, aw, 2030-sekretariatet, beteendepraktikan
```suggestion
tags: politik, vetenskap, klimat, aw, 2030-sekretariatet, beteendepraktikan
```

2023-04-13 17:52 UTC, docNord commented
Ping @mgcth

2023-04-13 18:29 UTC, mgcth approved these changes

2023-04-13 18:32 UTC, merged